

# This file was *autogenerated* from the file 01-concepts.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_1 = Integer(1)# R = Zmod(8)  # Example of a ring of integers modulo 8
# assert R(16) == R(0)  # 16 mod 8 is 0 in Zmod(8)


# This is valid Sage syntax
x = _sage_const_2 
y = x**_sage_const_3  + _sage_const_5    # Note: '^' is exponentiation in Sage, unlike Python's '**'
print(y)


# Define a variable in Sage
a = var('a')  # Creates a symbolic variable and assigns it to 'a'

# Define a polynomial ring
R = PolynomialRing(QQ, names=('x',)); (x,) = R._first_ngens(1)# Creates a polynomial ring R in variable x over the rational numbers QQ

# Define a polynomial
f = x**_sage_const_2  + _sage_const_3 *x + _sage_const_2   # Creates a polynomial f in the ring R

# Evaluate the polynomial at a specific value
result = f(_sage_const_1 )  # Evaluates f at x=1
print(result)  # Output: 6

