

# This file was *autogenerated* from the file 02-multi-linear-extension.sage
from sage.all_cmdline import *   # import sage library

_sage_const_7 = Integer(7); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0)
F = GF(_sage_const_7 )
R = F['a, b']; (a, b,) = R._first_ngens(2)

# Build eq(X, b) where:
# - variables is a tuple/list of Sage ring generators (x1, ..., x_n)
# - b is a Boolean tuple (0/1) of length n
# Returns a polynomial in the same ring as the variables
def eq_at_point(variables, b):
    n = len(variables)
    term = _sage_const_1 
    for i in range(n):
        xi = variables[i]
        bi = b[i]
        term *= (xi*bi + (_sage_const_1  - xi)*(_sage_const_1  - bi))
    return term

eq = eq_at_point((a, b), (_sage_const_1 , _sage_const_0 ))
print(eq)
print(eq(a=_sage_const_0 , b=_sage_const_0 ))
print(eq(a=_sage_const_0 , b=_sage_const_1 ))
print(eq(a=_sage_const_1 , b=_sage_const_0 ))
print(eq(a=_sage_const_1 , b=_sage_const_1 ))

